### ISSUE TITLE
USER STORY: Showing identity when submitting poll

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/My-First-Agile-Project#3]
As  being part of the **Love Running online community** I can **offer my personal feedback without showing my identity** so that **I can be honest and try make changes without causing arguments**

**Acceptance Criteria:**

- Acceptance Criteria 1: Option to hide identity (Tick the box).
- Acceptance Criteria 2:  Include a consent form explaining that information gathered will be analysed and brought forward within the community if necessary.

**Tasks**

- [ ] Add HTML and CSS to create a 'Tick box' which allows each voter to hide their identity
- [ ] Add JavaScript to hide account details if box is ticked
- [ ] Test feature functionality
