### ISSUE TITLE
USER STORY: Keep accessible record of all polls

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/My-First-Agile-Project#4]
As the **administrator** I can **keep a record of all of previous polls and results** so that **I can access it whenever I need to.**

**Acceptance Criteria:**

- Acceptance Criteria 1: Online database with administrator log in details.
- Acceptance Criteria 2:  Submitted polls must have a filter feature to extract relevant files efficiently.

**Tasks**

- [ ] Create an online data management system
- [ ] Include a form section with username and password fields
- [ ] Create one administrator account which can access recorded data
