### ISSUE TITLE
USER STORY: React to other comments

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/My-First-Agile-Project#5]
As a **voter** I can **react to other voter's comments** so that **the community can see if a comment is liked or disliked**

**Acceptance Criteria:**
- Acceptance Criteria 1: Add an emoji icon to each comment
- Acceptance Criteria 2: Include several emojis which represent emotions
- Acceptance Criteria 3: Display emojis at the bottom of each comment

**Tasks**
- [ ] Update HTML and CSS design to include an emoji button
- [ ] Include main emojis 
- [ ] Create a small area within the comment field where emojis selected are displayed
