### ISSUE TITLE
USER STORY: Start and hide polls 

### ISSUE THREAD

**Issue by AdamPillis** [AdamPillis/My-First-Agile-Project#6]
As an **administrator** I can **set a deadline on each poll** so that **votes are not accepted after some time**

**Acceptance Criteria:**
- Acceptance Criteria 1: Create a section where the administrator sets the end date of each poll. (year, month, day)
- Acceptance Criteria 2: Repeat for start date also
- Acceptance Criteria 3: To include time of day also hh:mm

**Tasks**
- [ ] Use HTML and CSS to design a new section to be built into set up process
- [ ] To include start and end data and time of each project using JavaScript
- [ ] Test if feature is displays and hides polls as requested

**Comment by AdamPillis** [comment]
This is completed
